name: Build
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: current
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test
