name: Publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Type of version bump'
        required: true
        default: 'minor'
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2.1.5
      with:
        node-version: '16'
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Bump Version
      run: npm version ${{ github.event.inputs.version }}
    - name: Push
      run: git push && git push --tags
    - name: Publish
      run: npm run deploy
